### ISSUE TITLE
LA- V2 Contradicting solutions

### ISSUE THREAD

**Issue by EiriniKilikian** [StevenClontz/checkit-svelte#10]
In the Linear Algebra questions, V2 Linear Combinations, the solutions to some questions in a) and b) are contradicting:

e.g. Question 15: the solution states (incorrectly) in a) that the associated linear system has no solutions; and in b) it states that there is a linear combination of the columns of the matrix that equal the vector of constants.

**Comment by StevenClontz** [comment]
Thanks for your contribution! This is an exercise bank issue, so I'll reopen in the corresponding repo.
